### ISSUE TITLE
Burn() transactions not deleting NFTs.

### ISSUE THREAD

**Issue by evanmcfarland** [tuminfei/icrc7_launchpad#5]
Use of the burn function does not delete the nft. Metadata, owner, etc., are still retrievable.

![Screenshot from 2024-06-28 14-56-03](https://github.com/tuminfei/icrc7_launchpad/assets/62383100/01b65af8-3b7d-42cb-84fc-40e96b1a51ed)

Everything else works great though. Thanks so much for this implementation Terry. I also had a similar implementation made that might be helpful to you and I'm deciding which to use: https://github.com/UncensoredGreats/NFT/

**Comment by tuminfei** [comment]
The implementation of the burn method does not delete, but transfers the token to a burn_address address (similar to a 0 address).

You can see the burn event by querying an nft event logs.

<img width="1273" alt="image" src="https://github.com/tuminfei/icrc7_launchpad/assets/275027/39f04122-4f62-4a47-949f-d5e22e2747e1">

**Comment by evanmcfarland** [comment]
If I'm not mistaken, tokens_of(), balance_of(), and owner_of() still show the principal and sub-account of the original holder before the burn. Is there a function that lets you know if an NFT is burned or not?

**Comment by tuminfei** [comment]
Thanks for your feedback, I have fixed the bug in the burn function.

**Comment by tuminfei** [comment]
If the problem has been solved, I will close this issue.
